from listas_2022 import *
#Creacion instancia
listaNumeros = ListaSimple()

#Adicion elementos
listaNumeros.adicionarAlInicio(1)
listaNumeros.adicionarAlInicio(2345)
listaNumeros.adicionarAlInicio(3)
listaNumeros.adicionarAlFinal(3)
listaNumeros.adicionarAlFinal(2)
listaNumeros.adicionarAlFinal(3)
listaNumeros.adicionarAlFinal(1)
listaNumeros.adicionarAlFinal(2)
listaNumeros.adicionarAlFinal(3)
listaNumeros.adicionarAlFinal(1)
listaNumeros.adicionarAlFinal(2)
listaNumeros.adicionarAlFinal(3)
listaNumeros.adicionarAlFinal(1)
listaNumeros.adicionarAlFinal(2)
listaNumeros.adicionarAlFinal(3)
listaNumeros.adicionarAlFinal(1)
listaNumeros.adicionarAlFinal(26)
listaNumeros.adicionarAlFinal(3)
print("Lista de Numero:",listaNumeros)
#listaNumeros.eliminarAparicionesDeUnDato(3)
#print(listaNumeros.eliminarPorPosicion(2))
#print("se repite ",listaNumeros.buscarYContarUnDato(1)," veces")
#print("Lista  con numeros eliminados")
listaNumeros.EliminarPenultimo()
print("Lista de Numero:",listaNumeros)
